### ISSUE TITLE
Phrase

### ISSUE THREAD

**Issue by martab0** [PJ-Woz/final-project#12]
This section contains the results for the settings available in Phrase. - nie trzeba tego zdania :-)

The fact that a feature does not work in GitHub preview does not mean it is caused by the incorrect output from the CAT. - można rozwinąć: Various flavours of Markdown render more sophisticated syntax differently on different platforms. (albo jakoś podobnie, ew. dodać odsyłacz do strony o flavours)

The test was carried out by checking the boxes in the settings. This made Phrase import more features and allowed more editing. However, if a feature started working, this is noted in the relevant section. -> The test was carried out by checking boxes in Phrase settings. This made Phrase import more features and allowed more editing. When a feature started working, it is noted in the relevant section. (o ile dobrze rozumiem sens)

🚨REALLY!: As a result, the escape sign \ was inserted in front of every backtick {`} symbol in the output file — code block does not work in the output. - Wcześniej jest "Code block was rendered normally.", więc rozumiem, że w Phrase codeblock wygląda dobrze, ale po eksporcie źle. Czego dotyczy "As a result"? 

Table syntax is rendered normally: - to, co na obrazku, nie wygląda "normally" :-(
As a result, the table does not work in the output file. - czego dotyczy "As a result"?

**Comment by PJ-Woz** [comment]
ad 1. Ok.

ad 2. Ok.

ad 3. Ok.

ad 4. Tak, we Phrase blok kodu wygląda ok, choć jest wrzucony jako tekst. Potem w pliku docelowym wrzuca `\`, co psuje działanie bloku kodu. Usunę "as a result". Phrase w tym ustawieniu, gdy coś zaimportował zwyczajnie, to potem dodawał te `\` przy eksporcie. Stąd "as a result". Dookreślę.

ad 5. Sama składnia tabeli jest wrzucona zwyczajnie, jako tekst. Tagi z pogrubienia itd. są tagami CAT-owskimi. Dookreślę. "As a result" - jw.

**Comment by PJ-Woz** [comment]
Zrobione
