### ISSUE TITLE
Trados

### ISSUE THREAD

**Issue by martab0** [PJ-Woz/final-project#13]
Figure 2: Trados editor with formatted text with tags - nie jest wyjaśnione jak to zrobić ani po co?

Trados does not render normally Markdown syntax, unless it is in code block. - nie rozumiem?

Trados displaces hover text and changes it between links: - nie rozumiem?

Reference does not work: the content in round brackets in [Składnia podstawowa](#basic-syntax) is not translatable - ujęłabym to bardziej jednoznacznie, np.:
Reference is not fully translatable: the display text in square brackets is translatable, but the reference content in round brackets is not translatableL [Składnia podstawowa](#basic-syntax)

Emoji is ignored, but it works in the output file. -> Emoji is ignored in the editor, but is preserved correctly in the output file.

HTML and other tags - nie rozumiem, co się wydarzyło

Content of the code block can be translated. - warto wyjaśnić, o co chodzi, np.:
Content of the code block can be translated. This is useful when you need to translate comments in code or messages from code.

The rest works as above. - The rest works as for basic settings.

Comment  is imported, but not  - czy chodzi o to, że tylko puste komentarze są importowane?

Embedded HTML is imported and can be translated. 
🚨REALLY!: However, HTML is rendered normally — the whole HTML code with all its tags. - nie rozumiem, co się dzieje z HTML-em

Encourage the translator to report any characters that are not used in a standard way in the source language - nie rozumiem?

**Comment by PJ-Woz** [comment]
Tutaj mnie chyba pokonał naukowo-logiczna hiperpedantyzm :)

ad 1. Figure 2 - to się po prostu samo wydarzyło. Podejrzewam, że gdy tekst łączy różne formatowanie, tak to Trados sobie zaznacza.

ad 2. tutaj chodzi tylko o to, że jest to wyrażone zwyczajnie w bloku kodu, czyli tak, jak być powinno. Czyli trados w bloku kodu nie tworzy nam swoich tagów, tylko zostawia `**text**`.

ad 3. Też tego nie rozumiem, co on robi, to widać w pliku docelowym. Czyli hover text z jednego odnośnika (np. z rekina) przerzuca do innego odnośnika (do Davida Bowie).

ad 4. Ok.

ad 5. Ok.

ad 6. W którym HTML and other tags? Bo dla każdego ustawienia jest inne.

ad 7. Ok.

ad 8. Ok~ish. To zależy od kontekstu :)

ad 9. Ok, to jest niejasne. W jednym ustawieniu te `<!-- komentarz -->` działają, a w innych nie. Chodzi o to, że jak czytamy wyniki od góry do dołu, to trzeba zaznaczyć, że w tym ustawieniu to znowu nie działa.

ad 10. Tutaj chodzi o to, że możemy tłumaczyć treść `<html> treści </html>`, ale ze wszystkimi tagami, które są edytowalne. Wcześniej te HTML-owskie treści były całkowicie ignorowane.

ad 11. W tej poradzie chodzi o to, że tłumacz ma zgłaszać tagi, ale on nie musi wiedzieć, że to są tagi. Stąd takie naokoło stwierdzenie, że jak coś wygląda "dziwnie", to ma to zgłosić.

**Comment by PJ-Woz** [comment]
Jednak mała zmiana: `Emoji is ignored, but it works in the output file.` to zostaje, bo z definicji wiadomo, że `ignored` jest w edytorze.

**Comment by PJ-Woz** [comment]
To `This is useful when you need to translate comments in code or messages from developers` wrzucam do zalet Tradosa. Komentarze dot. plusów, minusów i konsekwancji w samych wynikach staram się ograniczyć do minimum.
