### ISSUE TITLE
Wordfast Pro

### ISSUE THREAD

**Issue by martab0** [PJ-Woz/final-project#14]
There are cases in which tags are rendered normally as asterisks or underscore signs, e.g., when they are combined together, they are between characters other than spaces, or they are in a table; see Figure 3. - ja rozumiem, co się dzieje na obrazku, ale warto to opisać bardziej przystępnie (np. w którym wierszu jest dobrze :-)

it does not interpret extended syntax, like subscript, superscript, or footnote — they are ignored and rendered normally - chyba chodzi o to?
it does not interpret extended syntax, like subscript, superscript, or footnote — they are either ignored, or rendered as text

formatting (even standard Markdown formatting) in unrolled section is rendered as normal characters — this is most likely caused by embedding tags within HTML tags; however, some tags are rendered normally in Markdown tables - nie rozumiem?

inline code is always ignored: this is not translatable! - chodzi o to, że jest niewidoczny, jest tagiem czy jest wyświetlany jako zwykły tekst?

🚨REALLY!: Emoji was rendered as tags. It was expected that it would be either ignored or rendered normally. - dlaczego?

**Comment by PJ-Woz** [comment]
ad 1. Ok.

ad 2. Tak, operatory logiczne o poźnych godzinach już zaczynają płatać figle ;)

ad 3. Ok, tutaj patrzę do WF i nie wiem, czemu dałem to "however" teraz. Po prostu wszystkie tagi MD są wrzucone jako tekst. Do poprawy terminologia; WF pisałem jako pierwszy i potem to w kolejnych rundach mi umknęło ujednolicanie.

ad 4. Chodzi mi, że `ignored`, za definicją, nie jest wyświetlane w edytorze Wordfasta; `this is not translatable!` jest już komentarzem o konsekwencji tego ignorowania. Komentarz do usunięcia, bo to jest potem we wnioskach.

ad 5. To drugie zdanie miało poniekąd wytłumaczyć, czemu to jest "REALLY!". Po namyśle usunę "REALLY" i to zdanie, zostanie samo, że Emoji są wstawione jako tagi edytora.

Tutaj teraz myślę, że jeszcze doprecyzuję wszędzie jedną rzecz - te nieedytowalne tagi z edytora po prostu nazwę "CAT tags", bo się to potem może myli,ć z HTML tags czy Markdown tags.
