### ISSUE TITLE
Nazewnictwo

### ISSUE THREAD

**Issue by martab0** [PJ-Woz/final-project#15]
rendered normally — this means that Markdown or HTML tags are displayed with normal characters instead of tags inserted by the CAT
Zastanawiam się, jak to lepiej nazwać - może np. tak:
rendered as text — this means that Markdown or HTML tags are displayed with plain text characters instead of tags inserted by the CAT
("normally" sugerowałoby poprawne renderowanie)

tag - warto zdefiniować ten termin we wstępie, dodając, że jest "non-editable"

**Comment by PJ-Woz** [comment]
Tak, tego mi brakowało. Miałem problem z dobrym określeniem.

Przez "normally" chciałem oddać coś w stylu "zwyczajnie", ale faktycznie najlepiej ze sztuką będzie "as plain text", gdzie sugerowałaś w komentarzach do którychś wyników.

Czy przyjęcie "as plain text" będzie ok jako to, że jest po prostu tag wbity na twardo do edycji np. `**text**` zamiast `TAGtextTAG` albo `<kbd>text</kbd>` zamiast `TAGtextTAG`? Czy "as text"?

**Comment by martab0** [comment]
Wystarczy "rendered as text", bo jest krótsze - "as plain text" można dać w definicji.

**Comment by PJ-Woz** [comment]
Ok!
