### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by martab0** [PJ-Woz/final-project#16]
Inform the translator about basic Markdown syntax - tu możesz polecić swój przykładowy plik i inną stronę ze składnią Markdowna, do wyboru

What must or must not be translated with regard to syntax - przykłady: spis treści (nie trzeba, jeśli będzie generowany automatycznie); teksty opisujące adresy URL

How to open Markdown files to check the output file - może tak: How to view Markdown output files to ensure that the structure was preserved (for example....)

if some parts were not filtered by a CAT - if some parts were not handled properly by a CAT tool

Any characters that are not used in a standard way in the source language - o co chodzi?

it may be advisable to use several of them  - it may be advisable to try several of them

to open the Markdown files - to edit the Markdown files

check the output file - check the output file in the tool recommended by technical writer, or in any of these tools...

**Comment by PJ-Woz** [comment]
Zbiorcze ok :)

To `Any characters that are not used in a standard way in the source language` to jest to *roundabout* powiedzenie, że ma zgłaszać tagi :) Muszę to porządnie przeformułować.

**Comment by PJ-Woz** [comment]
Zamykam. Zostaje tylko dorzucenie poradnika o składni MD, ale to zrobię później.
