### ISSUE TITLE
Trados

### ISSUE THREAD

**Issue by martab0** [PJ-Woz/final-project#18]
The links in the headers lead to output files — the files translated with given settings.
- zdanie wpadło w dość zaskakujące miejsce
Contact the technical writer if characters are not used in a standard way in the source language
- może tak: Contact the technical writer if the source text contains unexpected characters - they may be part of Markdown syntax that Trados interpreted in a wrong way

**Comment by PJ-Woz** [comment]
Dałem: "Contact the technical writer if the source text in the CAT editor shows unexpected characters, as they may be part of Markdown or HTML syntax shown as text"
