### ISSUE TITLE
Nie wiem gdzie, ale trzeba objaśnić

### ISSUE THREAD

**Issue by martab0** [PJ-Woz/final-project#22]
...o co chodzi z tłumaczeniem kodu, komentarzy, referencji: może zrób podstronkę o tym, do której odsyłasz w tekście, kiedy jest mowa o tłumaczeniu dziwnych rzeczy? Nie wiem na ile chcesz naszpikować tekst odsyłaczami i czy odsyłać przy każdej wzmiance do kodu, czy tylko w General..., ale objaśnić trzeba. Coś tu piszę na rybkę, dodaj proszę przykłady dla kodu i referencji:

- You may or may not need to translate comments in Markdown, depending on use case; some comments have special meaning when producing outputs from Markdown and must not be translated, e.g. 
- In code blocks and inline code, you may need to translate comments, output messages, or even variable names 
- In references, you may need to translate the reference text in brackets ()... if it is actually localised

**Comment by PJ-Woz** [comment]
Na razie sam nie wiem, gdzie to umieścić indziej niż w w `ref-why-md-difficult.md`, czyli "Why is Markdown difficult for CATs?".

Dopisuję tam takie akapity do działu w stylu "things that may/may not be necessary to translate". Postaram się uniknąć zbytniego wybiegania w przyszłość.

Podlinkowuję w każdym rozdziale wyników do tego rozdziału, by było jakieś odniesienie.
