### ISSUE TITLE
Wrażenia ogólne i co dalej

### ISSUE THREAD

**Issue by martab0** [PJ-Woz/final-project#23]
Zrozumiałość tekstu podskoczyła tak z 5 razy, już jest dobrze i chyba powinnam przestać ingerować. Uwaga ogólna - ten rodzaj dokumentacji na pewno będzie czytany od środka, tj. większość użytkowników wejdzie tylko w ten kawałek, który ich interesuje (tabelka w Tradosie, hovery w Wordfaście, komentarze w Phrase itd.). Dlatego każda podstrona powinna być w pełni zrozumiała jako oddzielny dokument, z odsyłaczami do innych podstron tam, gdzie to wskazane. Na przykład rekomendacje dla tłumaczy i dla writerów na stronach Phrase, Tradosa i Wordfasta mogą odsyłać do General... Bardzo dobrze jest to już zrobione z Definitions.

Powodzenia w publikowaniu :-)

**Comment by PJ-Woz** [comment]
Zrobione! Podopisywałem jeszcze parę innych takich odnośników.
